export const PERMISSIONS = {
  VIEW_RECORDS: "VIEW_RECORDS",
  CREATE_RECORDS: "CREATE_RECORDS",
  UPDATE_RECORDS: "UPDATE_RECORDS",
  DELETE_RECORDS: "DELETE_RECORDS",
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_INSIGHTS: "VIEW_INSIGHTS",
  APPROVE_RECORDS: "APPROVE_RECORDS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
} as const;